services:
  - type: web
    name: sisgen-bm
    env: python
    buildCommand: "pip install -r requirements.txt && FLASK_APP=backend.app flask db upgrade"
    startCommand: "gunicorn --workers 1 --threads 4 --max-requests 500 --max-requests-jitter 50 'backend.app:create_app()'"
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      # A variável DATABASE_URL agora deve ser inserida MANUALMENTE no painel do Render!
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1
