"""Adiciona colunas de instrutor e workflow em Recurso

Revision ID: 075ed97867e6
Revises: ff22383c5994
Create Date: 2026-05-31 15:17:49.477924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '075ed97867e6'
down_revision = 'ff22383c5994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrutor_edicoes')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.alter_column('payload',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)

    with op.batch_alter_table('configuracoes_envio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_conf_envio_edicao_id'))
        batch_op.create_foreign_key(None, 'schools', ['escola_id'], ['id'])
        batch_op.create_foreign_key(None, 'edicoes', ['edicao_id'], ['id'])

    with op.batch_alter_table('processos_disciplina', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processos_disciplina_aluno_id'))
        batch_op.drop_index(batch_op.f('ix_processos_disciplina_regra_id'))
        batch_op.drop_index(batch_op.f('ix_processos_disciplina_relator_id'))

    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrutor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parecer_instrutor', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('decisao_comandante', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['instrutor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('decisao_comandante')
        batch_op.drop_column('parecer_instrutor')
        batch_op.drop_column('instrutor_id')

    with op.batch_alter_table('processos_disciplina', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processos_disciplina_relator_id'), ['relator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_disciplina_regra_id'), ['regra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_disciplina_aluno_id'), ['aluno_id'], unique=False)

    with op.batch_alter_table('configuracoes_envio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('fk_conf_envio_edicao_id'), ['edicao_id'], unique=False)

    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.alter_column('payload',
               existing_type=sa.Text(length=16777215),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    op.create_table('instrutor_edicoes',
    sa.Column('instrutor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('edicao_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], name=op.f('instrutor_edicoes_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], name=op.f('instrutor_edicoes_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrutor_id', 'edicao_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
