"""Initial PostgreSQL Migration

Revision ID: 087a4f39177e
Revises: 
Create Date: 2026-06-01 23:50:47.312522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087a4f39177e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npccal_type', sa.String(length=20), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('gravidade', sa.String(length=20), nullable=True),
    sa.Column('pontos', sa.Float(), nullable=False),
    sa.Column('atributo_fada_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discipline_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discipline_rules_npccal_type'), ['npccal_type'], unique=False)

    op.create_table('questionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', name='uq_school_nome'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('nome_completo', sa.String(length=120), nullable=True),
    sa.Column('nome_de_guerra', sa.String(length=50), nullable=True),
    sa.Column('posto_graduacao', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('is_totp_enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_logs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_logs_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_logs_user_id'), ['user_id'], unique=False)

    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('result_path', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('npccal_type', sa.String(length=20), nullable=True),
    sa.Column('fada_data_inicio', sa.DateTime(), nullable=True),
    sa.Column('fada_data_fim', sa.DateTime(), nullable=True),
    sa.Column('data_formatura', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('is_rr', sa.Boolean(), nullable=False),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('assinatura_padrao_path', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'school_id', name='uq_instrutor_user_school')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcm_token')
    )
    op.create_table('site_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.String(length=500), nullable=True),
    sa.Column('config_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('user_schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'school_id', name='uq_user_school')
    )
    op.create_table('ciclos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], name='fk_ciclo_edicao'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'school_id', 'edicao_id', name='uq_ciclo_nome_school_edicao')
    )
    op.create_table('configuracoes_envio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('materia', sa.String(length=100), nullable=False),
    sa.Column('envio_ativo', sa.Boolean(), nullable=True),
    sa.Column('edicao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escola_id', 'materia', 'edicao_id', name='uq_escola_mat_edicao_id')
    )
    op.create_table('opcoes_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ano', sa.String(length=20), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='EM_ANDAMENTO', nullable=False),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'school_id', name='uq_turma_nome_escola')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.String(length=20), nullable=True),
    sa.Column('opm', sa.String(length=50), nullable=False),
    sa.Column('num_aluno', sa.String(length=20), nullable=True),
    sa.Column('funcao_atual', sa.String(length=50), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_aluno')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia', sa.String(length=100), nullable=False),
    sa.Column('carga_horaria_prevista', sa.Integer(), nullable=False),
    sa.Column('carga_horaria_cumprida', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('materia', 'turma_id', name='_materia_turma_uc')
    )
    op.create_table('respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('opcao_resposta_id', sa.Integer(), nullable=True),
    sa.Column('texto_livre', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opcao_resposta_id'], ['opcoes_respostas.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('mostrar_periodo_13', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('mostrar_periodo_14', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('mostrar_periodo_15', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('mostrar_sabado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('periodos_sabado', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mostrar_domingo', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('periodos_domingo', sa.Integer(), server_default='0', nullable=False),
    sa.Column('priority_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('priority_disciplines', sa.Text(), nullable=True),
    sa.Column('priority_blocks', sa.Text(), nullable=True),
    sa.Column('blocked_blocks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delegacoes_prova',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('escola_gestora_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=True),
    sa.Column('escolas_fontes', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ),
    sa.ForeignKeyConstraint(['escola_gestora_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diarios_classe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_aula', sa.Date(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('conteudo_ministrado', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assinatura_path', sa.String(length=255), nullable=True),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.Column('instrutor_assinante_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['instrutor_assinante_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplina_turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pelotao', sa.String(length=50), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id_1', sa.Integer(), nullable=True),
    sa.Column('instrutor_id_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id_1'], ['instrutores.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id_2'], ['instrutores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elogios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('data_elogio', sa.Date(), nullable=False),
    sa.Column('data_registro', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('pontos', sa.Float(), nullable=False),
    sa.Column('atributo_1', sa.Integer(), nullable=True),
    sa.Column('atributo_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('elogios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elogios_aluno_id'), ['aluno_id'], unique=False)

    op.create_table('fada_avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('lancador_id', sa.Integer(), nullable=False),
    sa.Column('presidente_id', sa.Integer(), nullable=True),
    sa.Column('membro1_id', sa.Integer(), nullable=True),
    sa.Column('membro2_id', sa.Integer(), nullable=True),
    sa.Column('data_avaliacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('expressao', sa.Float(), nullable=False),
    sa.Column('planejamento', sa.Float(), nullable=False),
    sa.Column('perseveranca', sa.Float(), nullable=False),
    sa.Column('apresentacao', sa.Float(), nullable=False),
    sa.Column('lealdade', sa.Float(), nullable=False),
    sa.Column('tato', sa.Float(), nullable=False),
    sa.Column('equilibrio', sa.Float(), nullable=False),
    sa.Column('disciplina', sa.Float(), nullable=False),
    sa.Column('responsabilidade', sa.Float(), nullable=False),
    sa.Column('maturidade', sa.Float(), nullable=False),
    sa.Column('assiduidade', sa.Float(), nullable=False),
    sa.Column('pontualidade', sa.Float(), nullable=False),
    sa.Column('diccao', sa.Float(), nullable=False),
    sa.Column('lideranca', sa.Float(), nullable=False),
    sa.Column('relacionamento', sa.Float(), nullable=False),
    sa.Column('etica', sa.Float(), nullable=False),
    sa.Column('produtividade', sa.Float(), nullable=False),
    sa.Column('eficiencia', sa.Float(), nullable=False),
    sa.Column('media_final', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ndisc_snapshot', sa.Float(), nullable=False),
    sa.Column('aat_snapshot', sa.Float(), nullable=False),
    sa.Column('data_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_ass_pres', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_pres', sa.String(length=100), nullable=True),
    sa.Column('ip_pres', sa.String(length=45), nullable=True),
    sa.Column('data_ass_m1', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_m1', sa.String(length=100), nullable=True),
    sa.Column('ip_m1', sa.String(length=45), nullable=True),
    sa.Column('data_ass_m2', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_m2', sa.String(length=100), nullable=True),
    sa.Column('ip_m2', sa.String(length=45), nullable=True),
    sa.Column('data_assinatura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_integridade', sa.String(length=100), nullable=True),
    sa.Column('ip_assinatura', sa.String(length=45), nullable=True),
    sa.Column('user_agent_aluno', sa.String(length=255), nullable=True),
    sa.Column('texto_recurso', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['lancador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['membro1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['membro2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['presidente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('nota_p1', sa.Float(), nullable=True),
    sa.Column('nota_p2', sa.Float(), nullable=True),
    sa.Column('nota_rec', sa.Float(), nullable=True),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pelotao', sa.String(length=50), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('semana_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id_2', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id_2'], ['instrutores.id'], ),
    sa.ForeignKeyConstraint(['semana_id'], ['semanas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horarios_group_id'), ['group_id'], unique=False)

    op.create_table('processos_disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('relator_id', sa.Integer(), nullable=False),
    sa.Column('regra_id', sa.Integer(), nullable=True),
    sa.Column('codigo_infracao', sa.String(length=50), nullable=True),
    sa.Column('fato_constatado', sa.Text(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('pontos', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='AGUARDANDO_CIENCIA', nullable=False),
    sa.Column('data_ocorrencia', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_registro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_ciente', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_defesa', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_decisao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_notificacao_decisao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_recurso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_julgamento_recurso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('defesa', sa.Text(), nullable=True),
    sa.Column('decisao_final', sa.String(length=50), nullable=True),
    sa.Column('fundamentacao', sa.Text(), nullable=True),
    sa.Column('observacao_decisao', sa.Text(), nullable=True),
    sa.Column('detalhes_sancao', sa.Text(), nullable=True),
    sa.Column('texto_recurso', sa.Text(), nullable=True),
    sa.Column('decisao_recurso', sa.String(length=50), nullable=True),
    sa.Column('fundamentacao_recurso', sa.Text(), nullable=True),
    sa.Column('autoridade_recurso_id', sa.Integer(), nullable=True),
    sa.Column('is_crime', sa.Boolean(), nullable=False),
    sa.Column('tipo_sancao', sa.String(length=50), nullable=True),
    sa.Column('dias_sancao', sa.Integer(), nullable=False),
    sa.Column('origem_punicao', sa.String(length=20), nullable=False),
    sa.Column('ciente_aluno', sa.Boolean(), nullable=False),
    sa.Column('is_revelia', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['autoridade_recurso_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['regra_id'], ['discipline_rules.id'], ),
    sa.ForeignKeyConstraint(['relator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provas_recurso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes_banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=True),
    sa.Column('assunto', sa.String(length=255), nullable=True),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('alternativas', sa.JSON(), nullable=False),
    sa.Column('resposta_correta', sa.String(length=1), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurso_disciplinas_habilitadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disciplina_id')
    )
    op.create_table('turma_cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_nome', sa.String(length=100), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frequencias_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diario_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('justificativa', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['diario_id'], ['diarios_classe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rascunhos_prova',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegacao_id', sa.Integer(), nullable=False),
    sa.Column('questoes_selecionadas', sa.JSON(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delegacao_id'], ['delegacoes_prova.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('questao_texto', sa.Text(), nullable=False),
    sa.Column('argumentacao_texto', sa.Text(), nullable=True),
    sa.Column('arquivo_anexo', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('resposta_admin', sa.Text(), nullable=True),
    sa.Column('instrutor_id', sa.Integer(), nullable=True),
    sa.Column('parecer_instrutor', sa.Text(), nullable=True),
    sa.Column('decisao_comandante', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prova_id'], ['provas_recurso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recursos')
    op.drop_table('rascunhos_prova')
    op.drop_table('frequencias_alunos')
    op.drop_table('turma_cargos')
    op.drop_table('recurso_disciplinas_habilitadas')
    op.drop_table('questoes_banco')
    op.drop_table('provas_recurso')
    op.drop_table('processos_disciplina')
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horarios_group_id'))

    op.drop_table('horarios')
    op.drop_table('historico_disciplinas')
    op.drop_table('historico_alunos')
    op.drop_table('fada_avaliacoes')
    with op.batch_alter_table('elogios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elogios_aluno_id'))

    op.drop_table('elogios')
    op.drop_table('disciplina_turmas')
    op.drop_table('diarios_classe')
    op.drop_table('delegacoes_prova')
    op.drop_table('semanas')
    op.drop_table('respostas')
    op.drop_table('disciplinas')
    op.drop_table('alunos')
    op.drop_table('turmas')
    op.drop_table('opcoes_respostas')
    op.drop_table('configuracoes_envio')
    op.drop_table('ciclos')
    op.drop_table('user_schools')
    op.drop_table('site_configs')
    op.drop_table('push_subscriptions')
    op.drop_table('perguntas')
    op.drop_table('password_reset_tokens')
    op.drop_table('notifications')
    op.drop_table('instrutores')
    op.drop_table('image_assets')
    op.drop_table('edicoes')
    op.drop_table('background_jobs')
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_admin_logs_school_id'))

    op.drop_table('admin_logs')
    op.drop_table('users')
    op.drop_table('schools')
    op.drop_table('questionarios')
    with op.batch_alter_table('discipline_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discipline_rules_npccal_type'))

    op.drop_table('discipline_rules')
    # ### end Alembic commands ###
