"""Adiciona tabela FadaAvaliacao e relação com aluno

Revision ID: 103be8e972ac
Revises: ec5ff472a469
Create Date: 2025-11-12 19:54:20.341905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103be8e972ac'
down_revision = 'ec5ff472a469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fada_avaliacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_avaliador_custom', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fada_avaliacao', schema=None) as batch_op:
        batch_op.drop_column('nome_avaliador_custom')

    # ### end Alembic commands ###
