"""Torna gravidade opcional em DisciplineRule

Revision ID: 20ffcfc87550
Revises: 7a2463fe5fcb
Create Date: 2025-11-10 17:23:30.387714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20ffcfc87550'
down_revision = '7a2463fe5fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discipline_rules', schema=None) as batch_op:
        batch_op.alter_column('gravidade',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discipline_rules', schema=None) as batch_op:
        batch_op.alter_column('gravidade',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
