"""Isolamento Edicoes

Revision ID: 6f9ebc8e9a76
Revises: abf3858c792a
Create Date: 2026-05-27 02:42:34.829987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f9ebc8e9a76'
down_revision = 'abf3858c792a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('instrutor_edicoes',
    # sa.Column('instrutor_id', sa.Integer(), nullable=False),
    # sa.Column('edicao_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('instrutor_id', 'edicao_id')
    # )
    # op.drop_table('fada_avaliacao')
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('edicao_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('alunos_ibfk_2', type_='foreignkey')
        batch_op.drop_index('user_id')
        batch_op.create_index('user_id', ['user_id'])
        batch_op.create_foreign_key('alunos_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'edicoes', ['edicao_id'], ['id'])

    # with op.batch_alter_table('ciclos', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('nome'))

    # with op.batch_alter_table('processos_disciplina', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_processos_disciplina_aluno_id'))
    #     batch_op.drop_index(batch_op.f('ix_processos_disciplina_regra_id'))
    #     batch_op.drop_index(batch_op.f('ix_processos_disciplina_relator_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_disciplina', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processos_disciplina_relator_id'), ['relator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_disciplina_regra_id'), ['regra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_disciplina_aluno_id'), ['aluno_id'], unique=False)

    with op.batch_alter_table('ciclos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nome'), ['nome'], unique=True)

    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)
        batch_op.drop_column('edicao_id')

    op.create_table('fada_avaliacao',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avaliador_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_avaliacao', mysql.DATETIME(), nullable=False),
    sa.Column('attr_1_expressao', mysql.FLOAT(), nullable=False),
    sa.Column('attr_2_planejamento', mysql.FLOAT(), nullable=False),
    sa.Column('attr_3_perseveranca', mysql.FLOAT(), nullable=False),
    sa.Column('attr_4_apresentacao', mysql.FLOAT(), nullable=False),
    sa.Column('attr_5_lealdade', mysql.FLOAT(), nullable=False),
    sa.Column('attr_6_tato', mysql.FLOAT(), nullable=False),
    sa.Column('attr_7_equilibrio', mysql.FLOAT(), nullable=False),
    sa.Column('attr_8_disciplina', mysql.FLOAT(), nullable=False),
    sa.Column('attr_9_responsabilidade', mysql.FLOAT(), nullable=False),
    sa.Column('attr_10_maturidade', mysql.FLOAT(), nullable=False),
    sa.Column('attr_11_assiduidade', mysql.FLOAT(), nullable=False),
    sa.Column('attr_12_pontualidade', mysql.FLOAT(), nullable=False),
    sa.Column('attr_13_diccao', mysql.FLOAT(), nullable=False),
    sa.Column('attr_14_lideranca', mysql.FLOAT(), nullable=False),
    sa.Column('attr_15_relacionamento', mysql.FLOAT(), nullable=False),
    sa.Column('attr_16_etica', mysql.FLOAT(), nullable=False),
    sa.Column('attr_17_produtividade', mysql.FLOAT(), nullable=False),
    sa.Column('attr_18_eficiencia', mysql.FLOAT(), nullable=False),
    sa.Column('justificativa_notas', mysql.TEXT(), nullable=True),
    sa.Column('observacoes', mysql.TEXT(), nullable=True),
    sa.Column('adaptacao_carreira', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nome_avaliador_custom', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('fada_avaliacao_ibfk_1')),
    sa.ForeignKeyConstraint(['avaliador_id'], ['users.id'], name=op.f('fada_avaliacao_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('instrutor_edicoes')
    # ### end Alembic commands ###
