"""Adiciona DisciplineRule e campo npccal em School

Revision ID: 7a2463fe5fcb
Revises: 2b5b88901a2f
Create Date: 2025-11-10 14:35:47.302419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2463fe5fcb'
down_revision = '2b5b88901a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npccal_type', sa.String(length=20), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('gravidade', sa.String(length=20), nullable=False),
    sa.Column('pontos', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discipline_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discipline_rules_npccal_type'), ['npccal_type'], unique=False)

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('npccal_type', sa.String(length=20), server_default='cfs', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('npccal_type')

    with op.batch_alter_table('discipline_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discipline_rules_npccal_type'))

    op.drop_table('discipline_rules')
    # ### end Alembic commands ###
