"""Adiciona tabela de avaliacao atitudinal e itens

Revision ID: 8afd888e1f7a
Revises: f99377b21d7e
Create Date: 2025-11-10 19:54:34.127895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8afd888e1f7a'
down_revision = 'f99377b21d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaliacoes_atitudinais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('periodo_inicio',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('periodo_fim',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaliacoes_atitudinais', schema=None) as batch_op:
        batch_op.alter_column('periodo_fim',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('periodo_inicio',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
