"""add assinaturas recurso

Revision ID: a04a281525f8
Revises: ff9f811e0c08
Create Date: 2026-07-30 13:38:39.268079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04a281525f8'
down_revision = 'ff9f811e0c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamados_suporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=True),
    sa.Column('qso_contato', sa.String(length=255), nullable=False),
    sa.Column('tipo_login', sa.String(length=50), nullable=False),
    sa.Column('matricula_problema', sa.String(length=50), nullable=True),
    sa.Column('tipo_problema', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('anexo_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curso_videos', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assinatura_aluno', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('assinatura_instrutor', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('assinatura_comandante', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aluno_ciente', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('aluno_ciente_data', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aluno_ciente_ip', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('assinatura_padrao_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('assinatura_padrao_path')
        batch_op.drop_column('foto_perfil')

    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_column('aluno_ciente_ip')
        batch_op.drop_column('aluno_ciente_data')
        batch_op.drop_column('aluno_ciente')
        batch_op.drop_column('assinatura_comandante')
        batch_op.drop_column('assinatura_instrutor')
        batch_op.drop_column('assinatura_aluno')

    with op.batch_alter_table('curso_videos', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.drop_table('chamados_suporte')
    # ### end Alembic commands ###
