"""Cria a tabela Ciclo and adjusts the relationships

Revision ID: af9e7a05e31e
Revises: a00325d11bfc
Create Date: 2025-09-25 15:15:15.339242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9e7a05e31e'
down_revision = 'a00325d11bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciclos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciclo_id', sa.Integer(), nullable=False))
        # FIX: Added constraint_name
        batch_op.create_foreign_key('fk_disciplinas_ciclo_id', 'ciclos', ['ciclo_id'], ['id'])
        batch_op.drop_column('ciclo')

    with op.batch_alter_table('semanas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciclo_id', sa.Integer(), nullable=False))
        # FIX: Added constraint_name
        batch_op.create_foreign_key('fk_semanas_ciclo_id', 'ciclos', ['ciclo_id'], ['id'])
        batch_op.drop_column('ciclo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semanas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciclo', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.drop_constraint('fk_semanas_ciclo_id', type_='foreignkey')
        batch_op.drop_column('ciclo_id')

    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciclo', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.drop_constraint('fk_disciplinas_ciclo_id', type_='foreignkey')
        batch_op.drop_column('ciclo_id')

    op.drop_table('ciclos')
    # ### end Alembic commands ###