"""add assinaturas recurso

Revision ID: b04a281525f8
Revises: ff9f811e0c08
Create Date: 2026-07-30 13:38:39.268079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04a281525f8'
down_revision = 'a04a281525f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assinatura_aluno', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('assinatura_instrutor', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('assinatura_comandante', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aluno_ciente', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('aluno_ciente_data', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aluno_ciente_ip', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), server_default='default.png', nullable=False))
        batch_op.add_column(sa.Column('assinatura_padrao_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('assinatura_padrao_path')
        batch_op.drop_column('foto_perfil')

    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_column('aluno_ciente_ip')
        batch_op.drop_column('aluno_ciente_data')
        batch_op.drop_column('aluno_ciente')
        batch_op.drop_column('assinatura_comandante')
        batch_op.drop_column('assinatura_instrutor')
        batch_op.drop_column('assinatura_aluno')

    # ### end Alembic commands ###
