"""add assinaturas recurso

Revision ID: b04a281525f8
Revises: ff9f811e0c08
Create Date: 2026-07-30 13:38:39.268079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04a281525f8'
down_revision = 'a04a281525f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE recursos ADD COLUMN IF NOT EXISTS assinatura_aluno TEXT")
    op.execute("ALTER TABLE recursos ADD COLUMN IF NOT EXISTS assinatura_instrutor TEXT")
    op.execute("ALTER TABLE recursos ADD COLUMN IF NOT EXISTS assinatura_comandante TEXT")
    op.execute("ALTER TABLE recursos ADD COLUMN IF NOT EXISTS aluno_ciente BOOLEAN")
    op.execute("ALTER TABLE recursos ADD COLUMN IF NOT EXISTS aluno_ciente_data TIMESTAMP WITHOUT TIME ZONE")
    op.execute("ALTER TABLE recursos ADD COLUMN IF NOT EXISTS aluno_ciente_ip VARCHAR(50)")

    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS foto_perfil VARCHAR(255) DEFAULT 'default.png' NOT NULL")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS assinatura_padrao_path VARCHAR(255)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS assinatura_padrao_path")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS foto_perfil")

    op.execute("ALTER TABLE recursos DROP COLUMN IF EXISTS aluno_ciente_ip")
    op.execute("ALTER TABLE recursos DROP COLUMN IF EXISTS aluno_ciente_data")
    op.execute("ALTER TABLE recursos DROP COLUMN IF EXISTS aluno_ciente")
    op.execute("ALTER TABLE recursos DROP COLUMN IF EXISTS assinatura_comandante")
    op.execute("ALTER TABLE recursos DROP COLUMN IF EXISTS assinatura_instrutor")
    op.execute("ALTER TABLE recursos DROP COLUMN IF EXISTS assinatura_aluno")
    # ### end Alembic commands ###
