"""Restaura os campos is_rr e telefone para o modelo Instrutor

Revision ID: b2dbc702d529
Revises: 11b429cd9b29
Create Date: 2025-10-14 12:16:29.475257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2dbc702d529'
down_revision = '11b429cd9b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_rr', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_rr')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
