"""add_instrutor2_to_recursos

Revision ID: b4ee5b4370f9
Revises: b05254128ccb
Create Date: 2026-07-29 08:02:01.446025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ee5b4370f9'
down_revision = 'b05254128ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrutor2_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parecer_instrutor2', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['instrutor2_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parecer_instrutor2')
        batch_op.drop_column('instrutor2_id')
    # ### end Alembic commands ###
