"""Cria schema inicial padronizado com matricula

Revision ID: d5067750298a
Revises: 
Create Date: 2025-09-28 12:52:44.959115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5067750298a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('semanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('ciclo', sa.Integer(), server_default='1', nullable=False),
    sa.Column('mostrar_periodo_13', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('mostrar_periodo_14', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('mostrar_periodo_15', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('mostrar_sabado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('periodos_sabado', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mostrar_domingo', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('periodos_domingo', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('nome_completo', sa.String(length=120), nullable=True),
    sa.Column('nome_de_guerra', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('username')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia', sa.String(length=100), nullable=False),
    sa.Column('carga_horaria_prevista', sa.Integer(), nullable=False),
    sa.Column('ciclo', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('materia')
    )
    op.create_table('image_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especializacao', sa.String(length=100), nullable=False),
    sa.Column('formacao', sa.String(length=100), nullable=False),
    sa.Column('posto_graduacao', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('credor', sa.String(length=100), nullable=True),
    sa.Column('is_rr', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.String(length=500), nullable=True),
    sa.Column('config_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('user_schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'school_id', name='uq_user_school')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.String(length=20), nullable=True),
    sa.Column('opm', sa.String(length=50), nullable=False),
    sa.Column('num_aluno', sa.String(length=20), nullable=True),
    sa.Column('funcao_atual', sa.String(length=50), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_aluno'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('disciplina_turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pelotao', sa.String(length=50), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id_1', sa.Integer(), nullable=True),
    sa.Column('instrutor_id_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id_1'], ['instrutores.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id_2'], ['instrutores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pelotao', sa.String(length=50), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('semana_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ),
    sa.ForeignKeyConstraint(['semana_id'], ['semanas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcoes_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('nota_p1', sa.Float(), nullable=True),
    sa.Column('nota_p2', sa.Float(), nullable=True),
    sa.Column('nota_rec', sa.Float(), nullable=True),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('opcao_resposta_id', sa.Integer(), nullable=True),
    sa.Column('texto_livre', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opcao_resposta_id'], ['opcoes_respostas.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turma_cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_nome', sa.String(length=100), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_cargos')
    op.drop_table('respostas')
    op.drop_table('historico_disciplinas')
    op.drop_table('historico_alunos')
    op.drop_table('opcoes_respostas')
    op.drop_table('horarios')
    op.drop_table('disciplina_turmas')
    op.drop_table('alunos')
    op.drop_table('user_schools')
    op.drop_table('turmas')
    op.drop_table('site_configs')
    op.drop_table('perguntas')
    op.drop_table('password_reset_tokens')
    op.drop_table('instrutores')
    op.drop_table('image_assets')
    op.drop_table('disciplinas')
    op.drop_table('users')
    op.drop_table('semanas')
    op.drop_table('schools')
    op.drop_table('questionarios')
    # ### end Alembic commands ###
