"""Adiciona campo de fundamentacao aos processos disciplinares

Revision ID: d5fbf7580866
Revises: 8c44e60ca40a
Create Date: 2025-10-14 20:12:47.348576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fbf7580866'
down_revision = '8c44e60ca40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_disciplinares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fundamentacao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_disciplinares', schema=None) as batch_op:
        batch_op.drop_column('fundamentacao')

    # ### end Alembic commands ###
