"""Adiciona campo de observacao a horarios

Revision ID: da445aba4c21
Revises: 365d70a97fe4
Create Date: 2025-09-30 13:23:17.192264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da445aba4c21'
down_revision = '365d70a97fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.drop_column('observacao')

    # ### end Alembic commands ###
