"""Add detalhes_sancao to processo

Revision ID: e1b711a38a7c
Revises: d5fbf7580866
Create Date: 2025-10-15 09:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b711a38a7c'
down_revision = 'd5fbf7580866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_disciplinares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalhes_sancao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_disciplinares', schema=None) as batch_op:
        batch_op.drop_column('detalhes_sancao')

    # ### end Alembic commands ###