"""Adiciona tabela FadaAvaliacao e relação com aluno

Revision ID: ec5ff472a469
Revises: 8afd888e1f7a
Create Date: 2025-11-12 17:29:15.344631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5ff472a469'
down_revision = '8afd888e1f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fada_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('avaliador_id', sa.Integer(), nullable=False),
    sa.Column('data_avaliacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attr_1_expressao', sa.Float(), nullable=False),
    sa.Column('attr_2_planejamento', sa.Float(), nullable=False),
    sa.Column('attr_3_perseveranca', sa.Float(), nullable=False),
    sa.Column('attr_4_apresentacao', sa.Float(), nullable=False),
    sa.Column('attr_5_lealdade', sa.Float(), nullable=False),
    sa.Column('attr_6_tato', sa.Float(), nullable=False),
    sa.Column('attr_7_equilibrio', sa.Float(), nullable=False),
    sa.Column('attr_8_disciplina', sa.Float(), nullable=False),
    sa.Column('attr_9_responsabilidade', sa.Float(), nullable=False),
    sa.Column('attr_10_maturidade', sa.Float(), nullable=False),
    sa.Column('attr_11_assiduidade', sa.Float(), nullable=False),
    sa.Column('attr_12_pontualidade', sa.Float(), nullable=False),
    sa.Column('attr_13_diccao', sa.Float(), nullable=False),
    sa.Column('attr_14_lideranca', sa.Float(), nullable=False),
    sa.Column('attr_15_relacionamento', sa.Float(), nullable=False),
    sa.Column('attr_16_etica', sa.Float(), nullable=False),
    sa.Column('attr_17_produtividade', sa.Float(), nullable=False),
    sa.Column('attr_18_eficiencia', sa.Float(), nullable=False),
    sa.Column('justificativa_notas', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('adaptacao_carreira', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['avaliador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fada_avaliacao')
    # ### end Alembic commands ###
