"""Adiciona Avaliacao Atitudinal e pontos ao Processo

Revision ID: f99377b21d7e
Revises: 20ffcfc87550
Create Date: 2025-11-10 18:11:26.617644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f99377b21d7e'
down_revision = '20ffcfc87550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes_atitudinais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('avaliador_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('periodo_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('periodo_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('nota_disciplinar', sa.Float(), nullable=False),
    sa.Column('nota_fada', sa.Float(), nullable=False),
    sa.Column('nota_final', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['avaliador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacoes_atitudinais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_atitudinais_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_atitudinais_avaliador_id'), ['avaliador_id'], unique=False)

    op.create_table('processos_disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('relator_id', sa.Integer(), nullable=False),
    sa.Column('fato_constatado', sa.Text(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('pontos', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('Aguardando Ciência', 'Aluno Notificado', 'Defesa Enviada', 'Finalizado', name='status_processo_disciplinar'), nullable=False),
    sa.Column('data_ocorrencia', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_ciente', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_defesa', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_decisao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('defesa', sa.Text(), nullable=True),
    sa.Column('decisao_final', sa.String(length=50), nullable=True),
    sa.Column('fundamentacao', sa.Text(), nullable=True),
    sa.Column('detalhes_sancao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['relator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processos_disciplina', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processos_disciplina_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_disciplina_relator_id'), ['relator_id'], unique=False)

    op.create_table('avaliacao_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('criterio', sa.String(length=100), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes_atitudinais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacao_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacao_itens_avaliacao_id'), ['avaliacao_id'], unique=False)

    op.drop_table('processos_disciplinares')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processos_disciplinares',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relator_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fato_constatado', mysql.TEXT(), nullable=False),
    sa.Column('observacao', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('defesa', mysql.TEXT(), nullable=True),
    sa.Column('data_defesa', mysql.DATETIME(), nullable=True),
    sa.Column('decisao_final', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('data_decisao', mysql.DATETIME(), nullable=True),
    sa.Column('data_ocorrencia', mysql.DATETIME(), nullable=False),
    sa.Column('data_ciente', mysql.DATETIME(), nullable=True),
    sa.Column('fundamentacao', mysql.TEXT(), nullable=True),
    sa.Column('detalhes_sancao', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('processos_disciplinares_ibfk_1')),
    sa.ForeignKeyConstraint(['relator_id'], ['users.id'], name=op.f('processos_disciplinares_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('avaliacao_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacao_itens_avaliacao_id'))

    op.drop_table('avaliacao_itens')
    with op.batch_alter_table('processos_disciplina', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processos_disciplina_relator_id'))
        batch_op.drop_index(batch_op.f('ix_processos_disciplina_aluno_id'))

    op.drop_table('processos_disciplina')
    with op.batch_alter_table('avaliacoes_atitudinais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacoes_atitudinais_avaliador_id'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_atitudinais_aluno_id'))

    op.drop_table('avaliacoes_atitudinais')
    # ### end Alembic commands ###
