"""Remover restrição de unicidade global do nome do ciclo

Revision ID: ff22383c5994
Revises: aff76803dd78
Create Date: 2026-05-31 14:46:25.444882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff22383c5994'
down_revision = 'aff76803dd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Pega os índices da tabela ciclos
    indexes = inspector.get_indexes('ciclos')
    index_names = [index['name'] for index in indexes]
    
    with op.batch_alter_table('ciclos', schema=None) as batch_op:
        # Só remove se a restrição 'nome' existir no banco atual
        if 'nome' in index_names:
            batch_op.drop_constraint('nome', type_='unique')
            
        # Só cria a nova se não existir (evita crash se rodar de novo)
        if 'uq_ciclo_nome_school_edicao' not in index_names:
            batch_op.create_unique_constraint('uq_ciclo_nome_school_edicao', ['nome', 'school_id', 'edicao_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ciclos', schema=None) as batch_op:
        # Remove a restrição composta
        batch_op.drop_constraint('uq_ciclo_nome_school_edicao', type_='unique')
        # Volta a restrição única apenas pelo nome
        batch_op.create_unique_constraint('nome', ['nome'])

    # ### end Alembic commands ###
