"""Adiciona instrutor_id_2 a horarios

Revision ID: ff67dccfc78a
Revises: da445aba4c21
Create Date: 2025-10-06 13:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff67dccfc78a'
down_revision = 'da445aba4c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrutor_id_2', sa.Integer(), nullable=True))
        # CORREÇÃO: Adicionado um nome para a constraint
        batch_op.create_foreign_key(
            'fk_horarios_instrutor_id_2', 'instrutores',
            ['instrutor_id_2'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        # CORREÇÃO: Adicionado o nome da constraint para o drop
        batch_op.drop_constraint('fk_horarios_instrutor_id_2', type_='foreignkey')
        batch_op.drop_column('instrutor_id_2')

    # ### end Alembic commands ###