"""add_desligamentos

Revision ID: ff9f811e0c08
Revises: b4ee5b4370f9
Create Date: 2026-07-29 12:24:43.328893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9f811e0c08'
down_revision = 'b4ee5b4370f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_desligamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('data_desligamento', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_matricula', sa.String(length=20), nullable=False, server_default='Ativo'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_column('status_matricula')

    op.drop_table('registro_desligamentos')
    # ### end Alembic commands ###
