"""add_desligamentos

Revision ID: ff9f811e0c08
Revises: b4ee5b4370f9
Create Date: 2026-07-29 12:24:43.328893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9f811e0c08'
down_revision = 'b4ee5b4370f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamados_suporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=True),
    sa.Column('qso_contato', sa.String(length=255), nullable=False),
    sa.Column('tipo_login', sa.String(length=50), nullable=False),
    sa.Column('matricula_problema', sa.String(length=50), nullable=True),
    sa.Column('tipo_problema', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('anexo_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_desligamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('edicao_id', sa.Integer(), nullable=False),
    sa.Column('data_desligamento', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['edicao_id'], ['edicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_matricula', sa.String(length=20), nullable=False, server_default='Ativo'))

    with op.batch_alter_table('curso_videos', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso_videos', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_column('status_matricula')

    op.drop_table('registro_desligamentos')
    op.drop_table('chamados_suporte')
    # ### end Alembic commands ###
