# scripts/seed_npccal.py

from backend.models.database import db
from backend.models.discipline_rule import DisciplineRule
from sqlalchemy import delete
import click

CTSP_DATA = [
    {"codigo": "I", "descricao": "Movimentar-se em forma, sem prévia autorização;"},
    {"codigo": "II", "descricao": "Afastar-se do quartel sem tomar conhecimento do aditamento interno ou ordens e recomendações do dia, salvo se não constituir infração mais grave;"},
    {"codigo": "III", "descricao": "Demonstrar sonolência, desatenção ou displicência em qualquer atividade do CAl ou instrução;"},
    {"codigo": "IV", "descricao": "Não primar pela manutenção e limpeza das áreas de uso comum;"},
    {"codigo": "V", "descricao": "Deixar de comunicar ao Comandante do Pelotão, ou quem de direito, a mudança de endereço e telefones ou qualquer outro dado cadastral;"},
    {"codigo": "VI", "descricao": "Não manter limpo e devidamente organizado os locais de uso individual ou coletivo, quando sob sua responsabilidade;"},
    {"codigo": "VII", "descricao": "Não primar pelo bom estado de conservação e limpeza de material em carga ou enquanto responsável por este;"},
    {"codigo": "VIII", "descricao": "Deixar material abandonado ou em local que não deva permanecer;"},
    {"codigo": "IX", "descricao": "Deixar de cumprir regras básicas de segurança referente à utilização e condicionamento de armamento, salvo se não constituir infração mais grave;"},
    {"codigo": "X", "descricao": "Fazer entrega de material ou documento fora do prazo;"},
    {"codigo": "XI", "descricao": "Deixar de observar hábitos convencionais de higiene pessoal e coletiva;"},
    {"codigo": "XII", "descricao": "Não manter limpos e organizados pertences individuais ou coletivos;"},
    {"codigo": "XIII", "descricao": "Fumar em local não permitido;"},
    {"codigo": "XIV", "descricao": "Portar-se em local público sem observar a postura ou compostura peculiar a sua função, incluindo preceitos éticos de ordem social e/ou profissional;"},
    {"codigo": "XV", "descricao": "Dirigir-se a repartição ou a local restrito sem estar autorizado ou sem observar os procedimentos para tal;"},
    {"codigo": "XVI", "descricao": "Estar desatento na leitura do aditamento interno ou durante a transmissão de ordens;"},
    {"codigo": "XVII", "descricao": "Apresentar-se com fardamento incompleto, desalinhado, sujo, mal passado ou não regulamentar para o tipo de atividade a ser desenvolvida;"},
    {"codigo": "XVIII", "descricao": "Portar objeto, mesmo de uso particular, que contraste com o uniforme, não regulamentar, ou que deva possuir autorização para sua utilização;"},
    {"codigo": "XIX", "descricao": "Deixar de observar normas internas para o estacionamento de veículos;"},
    {"codigo": "XX", "descricao": "Deixar o aluno, mesmo no interior do aquartelamento ou local de funcionamento do curso, de portar a Carteira de Identidade Funcional (CIF) e o cartão do IPERGS ou outro Plano de Saúde, exceto quando trajando uniforme de saúde física;"},
    {"codigo": "XXI", "descricao": "Apresentar-se com o cabelo em desacordo com o estabelecido, bem como com a barba, unhas e pelos (pezinho, sobrancelha, etc);"},
    {"codigo": "XXII", "descricao": "Aproveitar-se, nas ocasiões em que se encontrar inserido na turma de aula, enquadrado na tropa ou em serviço, para ocultar sua autoria sobre irregularidades coibidas em regulamentos ou normas;"},
    {"codigo": "XXIII", "descricao": "Tecer comentários que gerem discórdias entre seus pares ou criem embaraços para a administração;"},
    {"codigo": "XXIV", "descricao": "Demonstrar-se passivo, na turma de aula ou na tropa, vindo a prejudicar o desempenho dos demais;"},
    {"codigo": "XXV", "descricao": "Deixar de comunicar ou tomar medidas corretivas ou disciplinares quando no exercício de comando, sobre qualquer aluno que esteja sob sua ordem;"},
    {"codigo": "XXVI", "descricao": "Deixar de observar rigorosamente os preceitos contidos em regulamentos ou normas;"},
    {"codigo": "XXVII", "descricao": "Deixar, quando na função de comando ou em serviço, de observar as prescrições afetas as suas funções contidas em regulamentos ou normas;"},
    {"codigo": "XXVIII", "descricao": "Dirigir-se à autoridade superior sem percorrer o canal competente;"},
    {"codigo": "XXIX", "descricao": "Extraviar, danificar ou deixar de encaminhar a quem de direito, documentos específicos ao ensino e outros normalizados pela instituição;"},
    {"codigo": "XXX", "descricao": "Entrar ou sair do local, ou ainda, participar ou afastar-se de formatura, onde esteja presente superior hierárquico, sem a devida permissão;"},
    {"codigo": "XXXI", "descricao": "Manter em sua posse qualquer material ou objeto de outrem, sem autorização, sem que constitua falta mais grave;"},
    {"codigo": "XXXII", "descricao": "Deixar de cumprir determinação de aluno em função de comando;"},
    {"codigo": "XXXIII", "descricao": "Cumprir parcialmente ou deturpar ordem recebida;"},
    {"codigo": "XXXIV", "descricao": "Retirar-se do local de instrução, sem permissão, ou dar ciência ao responsável do motivo arrazoado de seu afastamento;"},
    {"codigo": "XXXV", "descricao": "Tomar medidas de ordem administrativa ou disciplinar excedendo a sua esfera de atribuições ou contrariando aos preceitos regulamentares;"},
    {"codigo": "XXXVI", "descricao": "Deixar, quando em função de comando, de encaminhar em tempo hábil solicitação que deva ser solucionada pelo escalão superior;"},
    {"codigo": "XXXVII", "descricao": "Deixar de colocar a arma na arrecadação tão logo conclua serviços, instrução ou limpeza desta, salvo se não constituir infração mais grave;"},
    {"codigo": "XXXVIII", "descricao": "Remover material, da fazenda pública ou não, sem estar autorizado;"},
    {"codigo": "XXXIX", "descricao": "Comportar-se em local de instrução, estudo, atividade recreativa ou social de maneira inconveniente;"},
    {"codigo": "XL", "descricao": "Manter arma particular em administração policial militar sem estar autorizado;"},
    {"codigo": "XLI", "descricao": "Utilizar material não permitido, ou não dar conhecimento ao instrutor de sua posse, em instrução ou serviço;"},
    {"codigo": "XLII", "descricao": "Determinar formatura ou deslocamento de tropa sem estar na função de comando correspondente ou de representante legal na função ou autorização para tal;"},
    {"codigo": "XLIII", "descricao": "Perturbar, através de conversa, ruído e de outra maneira, o horário de silêncio relativo, o local de instrução ou de estudo;"},
    {"codigo": "XLIV", "descricao": "Comentar com pessoas estranhas ao Corpo de Alunos atos e fatos que só dizem respeito ao público interno;"},
    {"codigo": "XLV", "descricao": "Permitir que o aluno, durante o cumprimento de punição disciplinar, afaste-se do local determinado;"},
    {"codigo": "XLVI", "descricao": "Deixar, quando de hora ou turno de serviço, de tomar providências, por iniciativa própria, as quais, no senso comum, exijam sua intervenção;"},
    {"codigo": "XLVII", "descricao": "Apresentar atitude comportamental em relação à postura e compostura, quando no quarto de hora, em turno de serviço ou no transcorrer de todo o serviço, que prejudique o bom desempenho deste, ou denote desleixo com o mesmo;"},
    {"codigo": "XLVIII", "descricao": "Transitar fardado fora da área do quartel, sem estar de serviço ou autorizado;"},
    {"codigo": "XLIX", "descricao": "Deixar de comparecer ou de permanecer em local em que tenha sido determinada a sua presença, ou que deva receber fardamento, equipamento ou material;"},
    {"codigo": "L", "descricao": "Dirigir-se, referir-se ou responder de maneira desatenciosa ao aluno em função hierarquicamente superior, bem como a superior hierárquico, ou procurar desconsiderá-los;"},
    {"codigo": "LI", "descricao": "Afixar em local coletivo ou publicar em rede social, publicidades, anúncios e recados sem a devida autorização;"},
    {"codigo": "LII", "descricao": "Deixar de confeccionar parte escrita quando presenciar ou tomar conhecimento de qualquer irregularidade que deva tramitar ao canal superior;"},
    {"codigo": "LIII", "descricao": "Promover atividades comerciais nas dependências do OPM sem autorização;"},
    {"codigo": "LIV", "descricao": "Viajar para fora do Estado do Rio Grande do Sul sem comunicar o Corpo de Alunos;"},
    {"codigo": "LV", "descricao": "Afastar-se do quartel sem estar autorizado, salvo se não constituir infração mais grave;"},
    {"codigo": "LVI", "descricao": "Deixar o aluno em férias escolares ou dispensa, de regressar no prazo marcado à EsFAS, quando da conclusão desta ou quando tomar conhecimento da sua interrupção ou cancelamento, salvo se não constituir infração mais grave;"},
    {"codigo": "LVII", "descricao": "Assumir compromisso em nome do Corpo de Alunos ou da EsFAS, sem autorização;"},
    {"codigo": "LVIII", "descricao": "Demonstrar descontrole financeiro, afetando o conceito da BM junto à comunidade;"},
    {"codigo": "LIX", "descricao": "Deixar de saldar, ou não fazê-lo em tempo hábil, compromisso assumido com a administração da EsFAS;"},
    {"codigo": "LX", "descricao": "Afastar-se do seu local de serviço, quando em seu quarto de hora, sem que se constitua abandono;"},
    {"codigo": "LXI", "descricao": "Danificar material da fazenda estadual, salvo se não constituir infração mais grave;"},
    {"codigo": "LXII", "descricao": "Não ter o devido cuidado com doenças, principalmente infectocontagiosas, colocando em risco a coletividade;"},
    {"codigo": "LXIII", "descricao": "Atrasar-se para qualquer atividade diária do Corpo de Alunos sem um motivo de justificação, ou sem comunicar em tempo hábil o impedimento;"},
    {"codigo": "LXIV", "descricao": "Faltar a qualquer atividade diária do Corpo de Alunos sem um motivo de justificação, ou sem comunicar antecipadamente o impedimento;"},
    {"codigo": "LXV", "descricao": "Portar ou utilizar telefone móvel fora dos horários autorizados pelo Corpo de Aluno;"},
    {"codigo": "LXVI", "descricao": "Transitar no complexo da EsFAS trajando uniforme não previsto em aditamento Interno ou em desconformidade com o previsto pelo Corpo de Alunos, exetuando-se quando os Alunos estiverem em instrução com fardamento autorizado e previamente solicitado pelo instrutor, diferente ao previsto em aditamento;"},
    {"codigo": "LXVII", "descricao": "Deixar de fazer a manutenção do fuzil, quando for para isso determinado;"},
    {"codigo": "LXVIII", "descricao": "Deixar de ter nos seus armários, todos os fardamentos previstos no enxoval do CTSP;"},
    {"codigo": "LXIX", "descricao": "Sair da sala de aula, mesmo que com autorização do instrutor, por motivo fútil;"},
    {"codigo": "LXX", "descricao": "Transitar nas dependências do Corpo de Alunos nos horários previstos de sala de aula;"},
    {"codigo": "LXXI", "descricao": "Levar pessoa estranha, mesmo que familiar, às dependências do Corpo de Alunos sem a prévia autorização de Oficial do CAl;"},
    {"codigo": "LXXII", "descricao": "Utilizar qualquer dependência da EsFAS, fora do horário de expediente administrativo, sem a prévia autorização do responsável;"},
    {"codigo": "LXXIII", "descricao": "Realizar e/ou assistir instrução ou realizar atividade física quando houver determinação ou prescrição médica em contrário, salvo se não constituir infração mais grave;"},
    {"codigo": "LXXIV", "descricao": "Publicar na internet comentários ou fotos que não estejam autorizados referentes a assuntos internos;"},
    {"codigo": "LXXV", "descricao": "Interagir em redes sociais durante o horário de aula em que esteja presente o instrutor;"},
    {"codigo": "LXXVI", "descricao": "Publicar na internet conteúdo indecoroso que atente contra a imagem da Corporação."}
]

CBFPM_DATA = [
    {"codigo": "1", "descricao": "Faltar com a camaradagem para com colegas de instituição.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "2", "descricao": "Desrespeitar ou ser descortês para com colegas, policiais militares, servidores e civis.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "3", "descricao": "Desrespeitar regras de boas maneiras.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "4", "descricao": "Usar palavras de calão.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "5", "descricao": "Usar palavras de calão para ofender terceiro.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "6", "descricao": "Provocar animosidade entre alunos.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "7", "descricao": "Frequentar lugar não compatível com a condição policial militar.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "8", "descricao": "Concorrer, de qualquer forma, para luta corporal de colegas, policiais militares, servidores ou civis.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "9", "descricao": "Exteriorizar para com colega, policial militar ou servidor, através de ato, gesto, palavra ou escrito, comportamento de conotação indecorosa, sexual, amorosa ou de afeição íntima, em dependência ou área militar ou situação de serviço, ensino ou representação.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "10", "descricao": "Promover ou participar de jogo proibido ou aposta pecuniária em dependência ou área militar, pública ou particular, estando fardado, com uniforme da BMRS ou sendo reconhecido como policial militar.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "11", "descricao": "Assumir dívidas superiores às suas possibilidades, ou não saldá-las, após apresentar-se como policial militar para facilitar a transação.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "12", "descricao": "Faltar com respeito ou urbanidade para com policiais militares, servidores e civis em dependência ou área militar, pública ou particular, estando fardado, com uniforme da BMRS ou sendo reconhecido como policial militar.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "13", "descricao": "Provocar escândalo em dependência ou área militar, pública ou particular, estando fardado, com uniforme da BMRS ou sendo reconhecido como policial militar.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "14", "descricao": "Portar-se com má postura em dependência ou área militar, pública ou particular, estando fardado, com uniforme da BMRS ou sendo reconhecido como policial militar.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "15", "descricao": "Praticar ato incompatível com a moral, dignidade e os bons costumes, em dependência ou área militar, pública ou particular, estando fardado, com uniforme da BMRS ou sendo reconhecido como policial militar.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "16", "descricao": "Outras atitudes alheias ao comportamento militar que não afetem o pundonor militar e o decoro da classe.", "gravidade": "MÉDIA", "pontos": 0.3},
    {"codigo": "17", "descricao": "Demonstrar falta de interesse em instrução, palestra, representação ou outra atividade.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "18", "descricao": "Participar de aula prática com displicência.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "19", "descricao": "Não apresentar o material escolar que a instrução exigir.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "20", "descricao": "Obter nota inferior a 5,0 (cinco) nas Tarefas de Estudo (TEs).", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "21", "descricao": "Contatar servidor ou docente a fim de obter, para si ou para outrem, vantagem que prejudique a normalidade das atividades de ensino, aprendizagem e avaliação, ou que prejudique de qualquer forma os demais colegas de turma.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "22", "descricao": "Tentar usar de meio ilícito ou fraudulento na execução de qualquer atividade de ensino ou avaliação.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "23", "descricao": "Não conseguir expressar ideias e fatos com clareza e precisão, seja de forma escrita ou verbal.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "24", "descricao": "Chegar atrasado.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "25", "descricao": "Chegar atrasado com prejuízo ao ensino ou aprendizado.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "26", "descricao": "Chegar atrasado com prejuízo ao serviço.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "27", "descricao": "Entregar trabalho escolar com atraso.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "28", "descricao": "Não se levantar ao toque de alvorada.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "29", "descricao": "Entregar documento com atraso ou incorreção de procedimento.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "30", "descricao": "Entregar documento com atraso, gerando transtorno administrativo.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "31", "descricao": "Não entregar documentação exigida ou obrigatória.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "32", "descricao": "Apresentar Grupamento com atraso.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "33", "descricao": "Apresentar Grupamento com atraso causando prejuízo de instrução ou serviço.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "34", "descricao": "Render companheiro em serviço com atraso.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "35", "descricao": "Estar com o cabelo fora do padrão.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "36", "descricao": "Estar com barba por fazer.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "37", "descricao": "Faltar para com a higiene pessoal.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "38", "descricao": "Não preservar a limpeza das instalações.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "39", "descricao": "Estar com peça de uniforme, enxoval ou material sob sua cautela sujo.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "40", "descricao": "Estar com uniforme, enxoval ou material sob sua cautela amarrotado.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "41", "descricao": "Estar com uniforme, enxoval ou material sob sua cautela rasgado.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "42", "descricao": "Estar com uniforme desabotoado ou vestido fora do padrão.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "43", "descricao": "Estar com uniforme incompleto, combinação irregular de peças ou outras irregularidades.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "44", "descricao": "Estar com calçado ou adereços militares sem brilho.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "45", "descricao": "Deixar de portar a identidade funcional.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "46", "descricao": "Não possuir a identidade funcional.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "47", "descricao": "Transitar na OPM com trajes incompletos ou inadequados.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "48", "descricao": "Estar com cama, armário, carteira, sala de aula, alojamento ou qualquer outra dependência desorganizada.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "49", "descricao": "Deixar objetos ou equipamentos abandonados.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "50", "descricao": "Estar com armário desarrumado ou sujo.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "51", "descricao": "Executar mal faxina.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "52", "descricao": "Estar fora do local de faxina.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "53", "descricao": "Deixar armário aberto.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "54", "descricao": "Deixar armário sem fechadura, puxador ou identificação.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "55", "descricao": "Manter material sem identificação.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "56", "descricao": "Manter material do enxoval em mau estado de conservação.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "57", "descricao": "Estar com armamento sujo.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "58", "descricao": "Estar ou manter equipamento mal conservado.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "59", "descricao": "Abandonar armamento, equipamento ou material da Fazenda.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "60", "descricao": "Faltar com a verdade.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "61", "descricao": "Utilizar-se de anonimato para qualquer fim.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "62", "descricao": "Atribuir-se, falsamente, em qualquer situação, a qualidade de oficial da BMRS.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "63", "descricao": "Comportar-se com intimidade com policiais militares de outros círculos, sem a devida permissão.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "64", "descricao": "Promover reunião de qualquer natureza em recinto da BMRS, sem prévia autorização.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "65", "descricao": "Participar de reunião de qualquer natureza em recinto da BMRS, sem prévia autorização.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "66", "descricao": "Entrar ou sair das dependências da OPM por vias irregulares.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "67", "descricao": "Entrar ou sair das dependências do OPM sem apresentar-se a quem de direito.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "68", "descricao": "Sair da OPM sem autorização.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "69", "descricao": "Sair da sala de aula ou ausentar-se de instrução sem autorização.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "70", "descricao": "Introduzir, guardar ou manter consigo bebida alcoólica na área da OPM.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "71", "descricao": "Introduzir, guardar ou manter consigo arma branca ou de fogo irregular na área do OPM.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "72", "descricao": "Retirar qualquer documento ou objeto da BMRS das dependências do OPM, sem autorização.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "73", "descricao": "Extraviar ou danificar bem pertencente à Fazenda de forma dolosa.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "74", "descricao": "Extraviar ou danificar bem pertencente à Fazenda de forma culposa.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "75", "descricao": "Não observar normas vigentes na BMRS.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "76", "descricao": "Não observar prescrições regulamentares do Regulamento de Continências.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "77", "descricao": "Trabalhar mal como chefe de turma ou outra escala acadêmica.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "78", "descricao": "Não obedecer a ordem do chefe de turma ou cadete de serviço.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "79", "descricao": "Dificultar o comando do chefe de turma.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "80", "descricao": "Não cumprir ordem recebida.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "81", "descricao": "Ser displicente no cumprimento de ordens recebidas.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "82", "descricao": "Retardar cumprimento de ordens recebidas.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "83", "descricao": "Não comunicar missão cumprida.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "84", "descricao": "Deixar de prestar ao superior as manifestações de respeito previstas.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "85", "descricao": "Fumar em locais ou situações proibidas.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "86", "descricao": "Promover algazarra em lugar e hora impróprios.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "87", "descricao": "Não avançar ao rancho quando previsto ou avançar sem permissão.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "88", "descricao": "Perturbar o sossego ou a tranquilidade no âmbito do OPM.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "89", "descricao": "Perturbar o silêncio ou estudo dos colegas.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "90", "descricao": "Manter-se incorreto nas posições em forma.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "91", "descricao": "Mexer-se em forma.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "92", "descricao": "Falar em forma.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "93", "descricao": "Rir em forma.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "94", "descricao": "Não seguir os canais competentes de comandamento.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "95", "descricao": "Desconhecer escala de serviço.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "96", "descricao": "Transitar em recinto privativo da OPM sem prévia autorização.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "97", "descricao": "Transitar em área proibida, bem como, no corredor de alojamentos destinados a pessoas do sexo oposto, sem prévia autorização.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "98", "descricao": "Adentrar em alojamento destinado a pessoa do sexo oposto sem autorização.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "99", "descricao": "Convidar para que adentre em seu alojamento pessoa do sexo oposto ou qualquer pessoa sem autorização.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "100", "descricao": "Receber visita sem autorização ou em local não autorizado.", "gravidade": "MÉDIA", "pontos": 0.5},
    {"codigo": "101", "descricao": "Deixar de comunicar ao Comando falta ou irregularidade de que tenha conhecimento.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "102", "descricao": "Causar transtornos escolares, administrativos, cívico-militares ou policiais militares.", "gravidade": "LEVE", "pontos": 0.25},
    {"codigo": "103", "descricao": "Travar luta corporal com colega, policial militar, servidor civil ou civil.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "104", "descricao": "Desrespeitar superior hierárquico.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "105", "descricao": "Ofender a moral e os bons costumes por atos, palavras ou gestos.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "106", "descricao": "Manter relações sexuais ou praticar atos libidinos em área militar.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "107", "descricao": "Introduzir, distribuir, portar ou estar sob efeito de substâncias entorpecentes.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "108", "descricao": "Introduzir ou portar bebidas alcoólicas em área militar, bem como ingeri-las, salvo quando devidamente autorizado.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "109", "descricao": "Apresentar-se com sinais de embriaguez alcoólica ou sob efeito de outra substância entorpecente.", "gravidade": "GRAVE", "pontos": 1.0},
    {"codigo": "110", "descricao": "Deixar de fiscalizar o cumprimento das normas e ordens vigentes quando de serviço ou em função de comando.", "gravidade": "MÉDIA", "pontos": 0.5}
]

CSPM_DATA = [
    {"codigo": "R-1", "descricao": "Omitir informação relevante em registro de Livro de Partes Diárias;", "pontos": 0.2},
    {"codigo": "R-2", "descricao": "Omitir informação relevante em documento oficial, desde que não gere fato mais grave;", "pontos": 0.5},
    {"codigo": "R-3", "descricao": "Imputar falsa responsabilidade a terceiros;", "pontos": 3.0},
    {"codigo": "R-4", "descricao": "Tendo ciência de transgressão disciplinar de terceiros, não reportá-la espontaneamente;", "pontos": 0.2},
    {"codigo": "R-5", "descricao": "Tendo ciência de transgressão disciplinar de terceiros, não reportá-la se questionado por superior;", "pontos": 2.0},
    {"codigo": "R-6", "descricao": "Deixar de identificar corretamente o material em sua cautela, quando determinado;", "pontos": 0.75},
    {"codigo": "R-7", "descricao": "Deixar, na condição de chefe de turma, de reportar alteração de que deva saber a escala superior;", "pontos": 0.5},
    {"codigo": "R-8", "descricao": "Deixar de cumprir as prescrições relativas à arrumação de sua cama ou armário;", "pontos": 0.2},
    {"codigo": "R-9", "descricao": "Deixar de cumprir as prescrições relativas à arrumação da sala de aula;", "pontos": 0.5},
    {"codigo": "R-10", "descricao": "Deixar de cumprir as prescrições relativas à limpeza da APM;", "pontos": 0.5},
    {"codigo": "R-11", "descricao": "Deixar de cumprir as prescrições relativas a colocação de roupas e objetos no alojamento;", "pontos": 0.2},
    {"codigo": "R-12", "descricao": "Em dias de expediente, permanecer deitado após o horário de alvorada;", "pontos": 0.5},
    {"codigo": "R-13", "descricao": "Deixar de cumprir as prescrições relativas a utilização de instrumentos musicais e aparelhos que produzam som;", "pontos": 0.5},
    {"codigo": "R-14", "descricao": "Utilizar indevidamente os quadros informativos;", "pontos": 0.5},
    {"codigo": "R-15", "descricao": "Deixar de receber ou acompanhar autoridade que a isto tenha direito;", "pontos": 0.5},
    {"codigo": "R-16", "descricao": "Deixar de cumprir prescrições relativas a formaturas ou deslocamentos;", "pontos": 0.2},
    {"codigo": "R-17", "descricao": "Utilizar aparelho eletrônico quando não autorizado;", "pontos": 0.5},
    {"codigo": "R-18", "descricao": "Deixar de cumprir prescrições quanto a acomodação de bagagens no alojamento;", "pontos": 0.2},
    {"codigo": "R-19", "descricao": "Deixar de cumprir prescrições quanto ao transporte de objetos ou fardamentos a pé, dentro da APM;", "pontos": 0.5},
    {"codigo": "R-20", "descricao": "Deixar de cumprir atribuições, ou cumpri-las com desinteresse ou negligência;", "pontos": 0.2},
    {"codigo": "R-21", "descricao": "Deixar de cumprir atribuições, ou cumpri-las com desinteresse ou negligência durante o serviço de guarda;", "pontos": 0.75},
    {"codigo": "R-22", "descricao": "Deixar de cumprir prescrições quanto à ocupação de lugares em salas de aula, auditório, refeitório, etc.;", "pontos": 0.5},
    {"codigo": "R-23", "descricao": "Deixar de cumprir prescrições quanto à prática ou deslocamento para atividades esportivas;", "pontos": 0.2},
    {"codigo": "R-24", "descricao": "Apresentar documentos com erros gramaticais ou ortográficos, com rasuras ou falta de zelo em sua confecção;", "pontos": 0.75},
    {"codigo": "R-25", "descricao": "Apresentar-se com uniforme sem o devido zelo ou incompleto;", "pontos": 0.2},
    {"codigo": "R-26", "descricao": "Dormir, desde que não esteja de serviço, em horário ou local não permitido", "pontos": 0.5},
    {"codigo": "R-27", "descricao": "Deixar de conduzir, ou conduzir indevidamente, material para serviço ou instrução, especialmente EPI;", "pontos": 0.2},
    {"codigo": "R-28", "descricao": "Deixar de participar mudança de endereço ou número telefônico;", "pontos": 0.2},
    {"codigo": "R-29", "descricao": "Deixar de seguir prescrição médica devidamente receitada;", "pontos": 1.0},
    {"codigo": "R-30", "descricao": "Adentrar ou permanecer em dependência que lhe seja vedado, salvo se fato mais gravoso;", "pontos": 0.75},
    {"codigo": "R-31", "descricao": "Dirigir-se a autoridade sem observar a cadeia de comando", "pontos": 0.5},
    {"codigo": "R-32", "descricao": "Deixar de prestar sinais de respeito a uma tropa;", "pontos": 0.2},
    {"codigo": "R-33", "descricao": "Deixar de devolver materiais acautelado no prazo;", "pontos": 0.2},
    {"codigo": "R-34", "descricao": "Deixar de seguir normas relativas a estacionamento na APM;", "pontos": 0.2},
    {"codigo": "R-35", "descricao": "Ausentar-se da aula ou instrução sem autorização;", "pontos": 0.5},
    {"codigo": "R-36", "descricao": "Entregar documentação fora do prazo previamente estabelecido;", "pontos": 0.2},
    {"codigo": "R-37", "descricao": "Quando de serviço, autorizar aluno a praticar conduta em desacordo com as normas vigentes;", "pontos": 0.75},
    {"codigo": "R-38", "descricao": "Transmitir ou receber serviço fora do padrão estabelecido", "pontos": 0.2},
    {"codigo": "R-39", "descricao": "Retardar o a execução de ordem recebida;", "pontos": 0.75},
    {"codigo": "R-40", "descricao": "Deixar de realizar rondas previstas;", "pontos": 1.0},
    {"codigo": "R-41", "descricao": "Executar movimentos a pé firme ou em deslocamento com incorreção;", "pontos": 0.2},
    {"codigo": "R-42", "descricao": "Executar movimentos a pé firme ou em deslocamento com falta de energia ou empenho;", "pontos": 0.2},
    {"codigo": "R-43", "descricao": "Sentar-se durante o serviço de sentinela, salvo quando autorizado;", "pontos": 0.75},
    {"codigo": "R-44", "descricao": "Não atender aos toques de corneta;", "pontos": 0.2},
    {"codigo": "R-45", "descricao": "Não atender a aparelho telefônico funcional, quando na função de telefonista;", "pontos": 0.75},
    {"codigo": "R-46", "descricao": "Permitir, quando de serviço, a saída de material sem autorização de quem de direito, salvo se fato mais gravoso;", "pontos": 0.75},
    {"codigo": "R-47", "descricao": "Não realizar a rendição do plantão no horário determinado;", "pontos": 0.75},
    {"codigo": "R-48", "descricao": "Estudar ou ler material de outra disciplina durante instrução, salvo se expressamente autorizado;", "pontos": 0.5},
    {"codigo": "R-49", "descricao": "Deixar de ter o asseio pessoal necessário ao convívio no meio militar;", "pontos": 0.5},
    {"codigo": "R-50", "descricao": "Quando determinado, deixar de fazer, ou fazer inadequadamente a limpeza do alojamento ou outro local da APM;", "pontos": 0.75},
    {"codigo": "R-51", "descricao": "Eliminar resíduos em locais inadequados;", "pontos": 0.75},
    {"codigo": "R-52", "descricao": "Deixar de informar previamente atraso para alguma atividade;", "pontos": 0.75},
    {"codigo": "R-53", "descricao": "Deixar de informar, tão logo possível, o comparecimento a qualquer unidade médica ou similar, quando isto resultar atraso para atividades do aluno;", "pontos": 0.5},
    {"codigo": "R-54", "descricao": "Chegar atrasado a formatura ou instrução, embora em tempo de participar da mesma;", "pontos": 0.5},
    {"codigo": "R-55", "descricao": "Chegar atrasado a formatura ou instrução, resultando na não realização da atividade, com o atraso de até um período de expediente;", "pontos": 1.5},
    {"codigo": "R-56", "descricao": "Chegar atrasado a formatura ou instrução, resultando na não realização da atividade, com o atraso superior a um período de expediente;", "pontos": 2.5},
    {"codigo": "R-57", "descricao": "Faltar a um dia de atividades da APM;", "pontos": 1.0},
    {"codigo": "R-58", "descricao": "Faltar a 2 pernoites seguidos;", "pontos": 2.0},
    {"codigo": "R-59", "descricao": "Faltar a 3 ou mais pernoites seguidos;", "pontos": 3.0},
    {"codigo": "R-60", "descricao": "Permutar serviço sem autorização;", "pontos": 1.0},
    {"codigo": "R-61", "descricao": "Permutar o quarto de hora sem autorização do comandante da guarda;", "pontos": 0.75},
    {"codigo": "R-62", "descricao": "Comparecer em solenidade com uniforme diferente do determinado;", "pontos": 0.75},
    {"codigo": "R-63", "descricao": "Permanecer fora da sala de aula durante instruções sem autorização;", "pontos": 0.75},
    {"codigo": "R-64", "descricao": "Após o fim de qualquer licença, não se apresentar ao Corpo de Alunos;", "pontos": 1.5},
    {"codigo": "R-65", "descricao": "Representar a APM ou a Brigada Militar em ato, sem autorização;", "pontos": 2.0},
    {"codigo": "R-66", "descricao": "Permitir indisciplina, deixando de tomar providências, na condição de chefe de turma;", "pontos": 0.75},
    {"codigo": "R-67", "descricao": "Permitir indisciplina, deixando de tomar providências, na condição de auxiliar de pelotão, companhia, como membro do Estado Maior ou como auxiliar de Disciplina, em atividades do Corpo de Alunos;", "pontos": 0.75},
    {"codigo": "R-68", "descricao": "Deixar de cumprir suas obrigações quanto à organização da sala de aula, na condição de Aluno-Semana;", "pontos": 0.5},
    {"codigo": "R-69", "descricao": "Apresentar-se com uniforme mal passado em qualquer revista realizada;", "pontos": 0.2},
    {"codigo": "R-70", "descricao": "Apesentar-se com uniforme sujo, rasgado, descosturado ou sem algum botão;", "pontos": 0.5},
    {"codigo": "R-71", "descricao": "Apresentar-se com uniforme desajustado, com manequim visivelmente maior ou menor, proporcionando má apresentação individual;", "pontos": 0.5},
    {"codigo": "R-72", "descricao": "Manter a cama com roupa de cama suja;", "pontos": 0.5},
    {"codigo": "R-73", "descricao": "Manter a cama com arrumação fora do padrão;", "pontos": 0.2},
    {"codigo": "R-74", "descricao": "Manter o armário em condições anti-higiênicas;", "pontos": 0.5},
    {"codigo": "R-75", "descricao": "Apresentar-se, uniformizado, com barba, cabelo ou nuca (pezinho) mal aparados;", "pontos": 0.2},
    {"codigo": "R-76", "descricao": "Utilizar óculos com lentes escuras;", "pontos": 0.75},
    {"codigo": "R-77", "descricao": "Utilizar mochilas penduradas nos ombros ou pastas a tiracolo, salvo se militares e durante instrução;", "pontos": 0.75},
    {"codigo": "R-78", "descricao": "Utilizando uniforme, portar-se sem compostura;", "pontos": 0.5},
    {"codigo": "R-79", "descricao": "Apresentar-se em púbico, quando em atividade acadêmica, usando trajes civis inadequados à ocasião;", "pontos": 0.75},
    {"codigo": "R-80", "descricao": "Trocar de uniforme ou de trajes civis em local inadequado;", "pontos": 0.75},
    {"codigo": "R-81", "descricao": "Descumprir ordem relativa ao uso de trajes civis no interior da APM;", "pontos": 0.5},
    {"codigo": "R-82", "descricao": "Andar de mãos dadas, dar beijos, abraços prolongados ou outro tipo de manifestação de intimidade, quando no interior de OPM;", "pontos": 1.0},
    {"codigo": "R-83", "descricao": "Permanecer no alojamento durante as atividades de Saúde Física;", "pontos": 1.0},
    {"codigo": "R-84", "descricao": "Dançar de maneira excessivamente sensual ou provocativa, em ambiente destinado à dança, durante evento que frequente na condição de aluno;", "pontos": 1.0},
    {"codigo": "R-85", "descricao": "Hastear ou arriar as bandeiras do OPM de forma incorreta, ou deixar de hastear ou arriá-las;", "pontos": 0.5},
    {"codigo": "R-86", "descricao": "Conversar, rir ou fazer ruídos, quando em forma;", "pontos": 0.2},
    {"codigo": "R-87", "descricao": "Deixar de manter a imobilidade quando em forma, ou quando determinado;", "pontos": 0.2},
    {"codigo": "R-88", "descricao": "Como no item anterior, mas de serviço;", "pontos": 0.75},
    {"codigo": "R-89", "descricao": "Permitir que aluno que cumpre sanção disciplinar tenha em seu poder objetos ou instrumentos não permitidos, salvo se configurar infração mais grave;", "pontos": 1.0},
    {"codigo": "R-90", "descricao": "O Plantão ou Sentinela sentar-se durante o quarto de hora;", "pontos": 0.75},
    {"codigo": "R-91", "descricao": "Fumar durante o quarto de hora;", "pontos": 1.0},
    {"codigo": "R-92", "descricao": "Fumar em local não autorizado;", "pontos": 0.75},
    {"codigo": "R-93", "descricao": "Transitar desuniformizado pela APM, salvo deslocamento necessário para a entrada e saída do complexo do Departamento de Ensino, e salvo o interior dos alojamentos;", "pontos": 0.5},
    {"codigo": "R-94", "descricao": "Publicar em rede social, aplicativos de mensagens, sites, blogs, correios eletrônicos e semelhantes, fato que contribua para o desprestígio da corporação ou de qualquer um de seus integrantes;", "pontos": 1.0},
    {"codigo": "R-95", "descricao": "Estacionar seu veículo em local expressamente vedado aos alunos, quando de serviço ou em horário de expediente;", "pontos": 1.0},
    {"codigo": "R-96", "descricao": "Não portar documento de identidade funcional durante o serviço interno, exceto se utilizando uniforme de Saúde Física;", "pontos": 0.2},
    {"codigo": "R-97", "descricao": "Não portar documento de identidade funcional durante o serviço externo;", "pontos": 0.5},
    {"codigo": "R-98", "descricao": "Deixar de oferecer o melhor lugar disponível a oficial intermediário ou subalterno;", "pontos": 0.5},
    {"codigo": "R-99", "descricao": "Deixar de oferecer o melhor lugar disponível a oficial superior;", "pontos": 0.75},
    {"codigo": "R-100", "descricao": "Deixar de retribuir a continência de subordinado;", "pontos": 0.75},
    {"codigo": "R-101", "descricao": "Dirigir-se a superior demonstrando desconsideração ou pouco apreço pelas ordens emanadas;", "pontos": 0.75},
    {"codigo": "R-102", "descricao": "Dirigir-se a superior de forma manifestamente desatenciosa;", "pontos": 0.75},
    {"codigo": "R-103", "descricao": "Quando em função de assessoramento, omitir informações a superior, o induzindo ao erro, desde que sem maiores consequências;", "pontos": 1.5},
    {"codigo": "R-104", "descricao": "Participar de abaixo-assinado ou semelhantes para reivindicações ou críticas, em ambiente acadêmico;", "pontos": 1.5},
    {"codigo": "R-105", "descricao": "Estar com o cabelo ou unhas em desacordo com as normas estabelecidas pelo CAl;", "pontos": 0.2},
    {"codigo": "R-106", "descricao": "Omitir informação relevante para elucidar ou esclarecer fato;", "pontos": 0.75},
    {"codigo": "R-107", "descricao": "Andar sem cobertura regulamentar nas áreas descobertas da APM;", "pontos": 0.5},
    {"codigo": "R-108", "descricao": "Andar sem cobertura regulamentar quando autorizado a estar uniformizado fora da APM;", "pontos": 0.75},
    {"codigo": "R-109", "descricao": "Movimentar-se em forma, sem prévia autorização ou ficar escorado;", "pontos": 0.2},
    {"codigo": "R-110", "descricao": "Afastar-se do quartel sem tomar conhecimento do Boletim Interno, aditamento ou ordens e recomendações do dia, salvo se constituir infração mais grave;", "pontos": 1.0},
    {"codigo": "R-111", "descricao": "Demonstrar sonolência, desatenção ou displicência em qualquer atividade do CAl ou instrução;", "pontos": 0.2},
    {"codigo": "R-112", "descricao": "Não primar pela manutenção e limpeza das áreas de uso comum;", "pontos": 0.2},
    {"codigo": "R-113", "descricao": "Deixar de comunicar ao Auxiliar do Pelotão, ou quem de direito, a mudança de endereço e telefones ou qualquer outro dado cadastral;", "pontos": 0.2},
    {"codigo": "R-114", "descricao": "Não manter limpo e devidamente organizado os locais de uso individual ou coletivo, quando sob sua responsabilidade;", "pontos": 0.75},
    {"codigo": "R-115", "descricao": "Não primar pelo bom estado de conservação e limpeza de material em carga ou enquanto responsável por este;", "pontos": 0.5},
    {"codigo": "R-116", "descricao": "Deixar material abandonado ou em local que não deva permanecer;", "pontos": 0.2},
    {"codigo": "R-117", "descricao": "Deixar de cumprir regras básicas de segurança referente à utilização e condicionamento de armamento, salvo se constituir infração mais grave;", "pontos": 2.0},
    {"codigo": "R-118", "descricao": "Fazer entrega de material ou documento fora do prazo;", "pontos": 0.2},
    {"codigo": "R-119", "descricao": "Portar objeto, mesmo de uso particular, que contraste com o uniforme, não regulamentar, ou que deva possuir autorização para sua utilização;", "pontos": 0.2},
    {"codigo": "R-120", "descricao": "Demonstrar-se passivo, na turma de aula ou na tropa, vindo a prejudicar o desempenho dos demais;", "pontos": 0.5},
    {"codigo": "R-121", "descricao": "Entrar ou sair do local, ou ainda, participar ou afastar-se de formatura, onde esteja presente superior hierárquico, sem a devida permissão;", "pontos": 0.5},
    {"codigo": "R-122", "descricao": "Retirar-se do local de instrução, sem permissão, ou dar ciência ao responsável do motivo arrazoado de seu afastamento;", "pontos": 0.5},
    {"codigo": "R-123", "descricao": "Tomar medidas de ordem administrativa ou disciplinar excedendo a sua esfera de atribuições ou contrariando aos preceitos regulamentares;", "pontos": 0.2},
    {"codigo": "R-124", "descricao": "Deixar, quando em função de comando, de encaminhar em tempo hábil solicitação que deva ser solucionada pelo escalão superior;", "pontos": 0.2},
    {"codigo": "R-125", "descricao": "Deixar de colocar a arma na arrecadação tão logo conclua serviços, instrução ou limpeza desta, salvo se constituir infração mais grave;", "pontos": 0.5},
    {"codigo": "R-126", "descricao": "Manter arma particular em administração policial militar sem estar autorizado;", "pontos": 0.75},
    {"codigo": "R-127", "descricao": "Determinar formatura ou deslocamento de tropa sem estar na função de comando correspondente ou de representante legal na função ou autorização para tal;", "pontos": 0.5},
    {"codigo": "R-128", "descricao": "Perturbar, através de conversa, ruído e de outra maneira, o horário de silêncio relativo, o local de instrução ou de estudo;", "pontos": 0.5},
    {"codigo": "R-129", "descricao": "Comentar com pessoas estranhas ao Corpo de Alunos atos e fatos que só dizem respeito ao público interno;", "pontos": 0.2},
    {"codigo": "R-130", "descricao": "Permitir que o aluno, durante o cumprimento de punição disciplinar, afaste se do local determinado;", "pontos": 2.0},
    {"codigo": "R-131", "descricao": "Deixar, quando de hora ou turno de serviço, de tomar providências, por iniciativa própria, as quais, no senso comum, exijam sua intervenção;", "pontos": 0.5},
    {"codigo": "R-132", "descricao": "Transitar fardado fora da área do quartel, sem estar de serviço ou autorizado;", "pontos": 1.0},
    {"codigo": "R-133", "descricao": "Deixar de comparecer ou de permanecer em local em que tenha sido determinada a sua presença, ou que deva receber fardamento, equipamento ou material;", "pontos": 0.5},
    {"codigo": "R-134", "descricao": "Dirigir-se, referir-se ou responder de maneira desatenciosa ao aluno em função hierarquicamente superior, bem como a superior hierárquico, ou procurar desconsiderá-los;", "pontos": 0.5},
    {"codigo": "R-135", "descricao": "Promover atividades comerciais nas dependências do OPM sem autorização;", "pontos": 0.75},
    {"codigo": "R-136", "descricao": "Afastar-se do quartel sem estar autorizado, salvo se constituir infração mais grave;", "pontos": 0.5},
    {"codigo": "R-137", "descricao": "Viajar para fora do Estado do Rio Grande do Sul sem guia de trânsito ou, portando-a, deixar de apresentar-se em seu destino à autoridade competente;", "pontos": 1.0},
    {"codigo": "R-138", "descricao": "Deixar o aluno em férias escolares ou dispensa, de regressar no prazo marcado ao OPM, quando da conclusão desta ou quando tomar conhecimento da sua interrupção ou cancelamento, salvo se constituir infração mais grave;", "pontos": 0.75},
    {"codigo": "R-139", "descricao": "Deixar o aluno em férias escolares ou dispensa, de regressar no prazo;", "pontos": 1.0},
    {"codigo": "R-140", "descricao": "Assumir compromisso em nome do Corpo de Alunos ou da OPM de Ensino, sem autorização;", "pontos": 1.5},
    {"codigo": "R-141", "descricao": "Demonstrar descontrole financeiro, afetando o conceito da BM junto à comunidade;", "pontos": 0.75},
    {"codigo": "R-142", "descricao": "Deixar de saldar, ou não fazê-lo em tempo hábil, compromisso assumido com administração da OPM;", "pontos": 0.75},
    {"codigo": "R-143", "descricao": "Afastar-se do seu local de serviço, quando em seu quarto de hora, sem que se constitua abandono;", "pontos": 0.75},
    {"codigo": "R-144", "descricao": "Danificar material da fazenda estadual, salvo se constituir infração mais grave;", "pontos": 0.75},
    {"codigo": "R-145", "descricao": "Portar ou utilizar telefone móvel fora dos horários autorizados pelo Corpo de Alunos.", "pontos": 0.5},
    {"codigo": "R-146", "descricao": "Deixar de ter nos seus armários, todos os fardamentos recebidos por ocasião da inclusão ao CAl;", "pontos": 0.5},
    {"codigo": "R-147", "descricao": "Sair da sala de aula, mesmo que com autorização do instrutor, por motivo fútil;", "pontos": 0.2},
    {"codigo": "R-148", "descricao": "Transitar nas dependências do Corpo de Alunos nos horários previstos de sala de aula;", "pontos": 0.2},
    {"codigo": "R-149", "descricao": "Levar pessoa estranha, mesmo que familiar, às dependências do Corpo de Alunos sem a prévia autorização de Oficial do CAl;", "pontos": 0.5},
    {"codigo": "R-150", "descricao": "Realizar e/ou assistir instrução ou realizar atividade física quando houver determinação ou prescrição médica em contrário, salvo se constituir infração mais grave;", "pontos": 1.5},
    {"codigo": "R-151", "descricao": "Publicar na internet comentários ou fotos que não estejam autorizados referentes a assuntos internos;", "pontos": 0.75},
    {"codigo": "R-152", "descricao": "Interagir em redes sociais durante o horário de aula em que esteja presente o instrutor;", "pontos": 0.5},
    {"codigo": "R-153", "descricao": "Não dar o retorno de missão que lhe foi designada;", "pontos": 0.75},
    {"codigo": "R-154", "descricao": "Efetuar contato direto com instrutor sem a devida autorização;", "pontos": 0.5},
    {"codigo": "R-155", "descricao": "Não repassar ordens recebidas;", "pontos": 0.2},
    {"codigo": "R-156", "descricao": "Não repassar ordens a terceiros, quando expressamente determinado;", "pontos": 0.5},
    {"codigo": "R-157", "descricao": "Na atividade de fiscalização, durante o serviço de guarda, não observar irregularidades por parte da tropa fiscalizada;", "pontos": 0.5},
    {"codigo": "R-158", "descricao": "Deixar de participar irregularidades observadas;", "pontos": 0.2},
    {"codigo": "R-159", "descricao": "Não informar, via canal de comando, o retorno ao quartel após dispensa;", "pontos": 0.5},
    {"codigo": "R-160", "descricao": "Deixar material elétricou ou eletrônico ligado sem estar presente;", "pontos": 0.5},
    {"codigo": "R-161", "descricao": "Consumir alimentos e/ou bebidas fora do local adequado;", "pontos": 0.5},
    {"codigo": "R-162", "descricao": "Transitar pelas dependências da Academia de Polícia Militar com alimentos e/ou bebidas durante o horário de instrução ou sob determinação de cumprimento de missão pelo Cal.", "pontos": 0.2},
    {"codigo": "R-163", "descricao": "Não cumprir adequadamente suas funções de chefe de turma ou de aluno-semana.", "pontos": 0.5},
    {"codigo": "R-164", "descricao": "Durante o cumprimento de missão, conversar em demasia, agir de maneira displiscente ou sem dedicação à tarefa atribuída.", "pontos": 0.2},
    {"codigo": "R-165", "descricao": "Ausentar-se do local de cumprimento de tarefa sem autorização;", "pontos": 0.5},
    {"codigo": "R-166", "descricao": "Ausentar-se do local de cumprimento de tarefa sem autorização, e com inequívoca intenção de não participar do cumprimento da missão;", "pontos": 0.75},
    {"codigo": "R-167", "descricao": "Contrariar determinação expressa de aluno em função de comando ou de militar mais antigo pertencente ao efetivo orgânico da APM.", "pontos": 0.75},
    {"codigo": "R-168", "descricao": "No serviço de guarda, não realizar as rondas durante o período determinado.", "pontos": 0.75},
    {"codigo": "R-169", "descricao": "Dirigir-se a qualquer das seções, ao subcomando ou ao comando da Academia de Polícia Militar sem a observação do canal de comando.", "pontos": 0.2},
    {"codigo": "R-170", "descricao": "Preencher incorretamente e/ou encaminhar documento com rasura, sujo ou amassado ao CAl, ou à Seção de Ensino, quando aplicável;", "pontos": 0.5},
    {"codigo": "R-171", "descricao": "Omitir-se, quando em qualquer função de comando ou Estado Maior do Batalhão Escola, de reportar irregularidades que verifique;", "pontos": 0.5},
    {"codigo": "R-172", "descricao": "Não realizar a fiscalização da tropa sob seu comando no que se refere à NPCCAL.", "pontos": 0.5},
]


def seed_rules():
    """
    Limpa e preenche a tabela DisciplineRule com os dados dos 3 NPCCALs.
    """
    try:
        click.echo("Limpando regras de disciplina existentes...")
        db.session.execute(delete(DisciplineRule))
        
        # --- CTSP (Sargentos) ---
        click.echo(f"Inserindo {len(CTSP_DATA)} regras do NPCCAL - CTSP...")
        for r in CTSP_DATA:
            db.session.add(DisciplineRule(
                npccal_type='ctsp',
                codigo=r['codigo'],
                descricao=r['descricao'],
                gravidade='N/A', # Sem gravidade definida
                pontos=0.0      # Sem pontuação
            ))

        # --- CBFPM (Soldados) ---
        click.echo(f"Inserindo {len(CBFPM_DATA)} regras do NPCCAL - CBFPM...")
        for r in CBFPM_DATA:
            db.session.add(DisciplineRule(
                npccal_type='cbfpm',
                codigo=r['codigo'],
                descricao=r['descricao'],
                gravidade=r['gravidade'],
                pontos=r['pontos']
            ))

        # --- CSPM (Oficiais) ---
        click.echo(f"Inserindo {len(CSPM_DATA)} regras do NPCCAL - CSPM...")
        for r in CSPM_DATA:
            db.session.add(DisciplineRule(
                npccal_type='cspm',
                codigo=r['codigo'],
                descricao=r['descricao'],
                gravidade=None, # Sem gravidade, conforme PDF
                pontos=r['pontos']
            ))

        db.session.commit()
        click.echo("="*30)
        click.echo("DADOS DOS NPCCALS INSERIDOS COM SUCESSO!")
        click.echo(f"Total CTSP: {len(CTSP_DATA)} regras.")
        click.echo(f"Total CBFPM: {len(CBFPM_DATA)} regras.")
        click.echo(f"Total CSPM: {len(CSPM_DATA)} regras.")
        click.echo("="*30)

    except Exception as e:
        db.session.rollback()
        click.echo(f"ERRO AO INSERIR REGRAS: {e}")