"""Adiciona colunas de instrutor e workflow em Recurso

Revision ID: 075ed97867e6
Revises: ff22383c5994
Create Date: 2026-05-31 15:17:49.477924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '075ed97867e6'
down_revision = 'ff22383c5994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrutor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parecer_instrutor', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('decisao_comandante', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_recursos_instrutor_id', 'users', ['instrutor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recursos_instrutor_id', type_='foreignkey')
        batch_op.drop_column('decisao_comandante')
        batch_op.drop_column('parecer_instrutor')
        batch_op.drop_column('instrutor_id')
    # ### end Alembic commands ###
