"""Adiciona tabela de processos disciplinares

Revision ID: 11b429cd9b29
Revises: f90660c88e74
Create Date: 2025-10-14 10:43:28.290307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11b429cd9b29'
down_revision = 'f90660c88e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processos_disciplinares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('relator_id', sa.Integer(), nullable=False),
    sa.Column('fato_constatado', sa.Text(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('defesa', sa.Text(), nullable=True),
    sa.Column('data_defesa', sa.DateTime(), nullable=True),
    sa.Column('decisao_final', sa.String(length=100), nullable=True),
    sa.Column('data_decisao', sa.DateTime(), nullable=True),
    sa.Column('data_ocorrencia', sa.DateTime(), nullable=False),
    sa.Column('data_ciente', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['relator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('user_id'))
        batch_op.drop_column('telefone')
        batch_op.drop_column('is_rr')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_column('token_hash')
        batch_op.drop_column('attempts')
        batch_op.drop_column('max_attempts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_attempts', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('attempts', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('token_hash', mysql.VARCHAR(length=256), nullable=False))

    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rr', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('telefone', mysql.VARCHAR(length=15), nullable=True))
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)

    op.drop_table('processos_disciplinares')
    # ### end Alembic commands ###
