"""Remove campos descontinuados de instrutor

Revision ID: a00325d11bfc
Revises: d5067750298a
Create Date: 2025-09-28 14:33:38.920274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00325d11bfc'
down_revision = 'd5067750298a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.drop_column('formacao')
        batch_op.drop_column('especializacao')
        batch_op.drop_column('credor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credor', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('especializacao', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('formacao', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
