"""Add edicao_id to Ciclo

Revision ID: a3a4f05633e1
Revises: 6f9ebc8e9a76
Create Date: 2026-05-27 20:27:24.486150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a4f05633e1'
down_revision = '6f9ebc8e9a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ciclos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edicao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ciclo_edicao', 'edicoes', ['edicao_id'], ['id'])



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('ciclos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ciclo_edicao', type_='foreignkey')
        batch_op.drop_column('edicao_id')

    # ### end Alembic commands ###
