"""Adiciona carga horaria cumprida a disciplina

Revision ID: a76506570530
Revises: b2dbc702d529
Create Date: 2025-10-14 16:49:30.809662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76506570530'
down_revision = 'b2dbc702d529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carga_horaria_cumprida', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.drop_column('carga_horaria_cumprida')

    # ### end Alembic commands ###
